### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by brittGit** [xynxynxyn/terminal-discord#10]
Is there a reason you haven't published to npm? If you have instructions for making the config file it should work by installing through npm.

**Comment by Dids** [comment]
As a workaround, you can actually install it by running `npm i -g xynxynxyn/terminal-discord`, since `npm` supports installing packages straight from GitHub.

**Comment by xynxynxyn** [comment]
Implemented a simple default config creation dialogue and published to npm [here.](https://www.npmjs.com/package/terminal-discord).
