### ISSUE TITLE
Crashes when selecting a server with 35+ channels

### ISSUE THREAD

**Issue by yucachaaaan** [xynxynxyn/terminal-discord#2]
Just bumped onto this client when randomly looking out for a Discord client. There's one thing I noticed though when testing around : 

1. Run terminal-discord as usual
2. Open the channel selection menu
3. Select a server that has 35+ channels  
    
This happens when I select it : 

```
/home/ymzk/terminal-discord/node_modules/readline-sync/lib/readline-sync.js:1259  
    throw '`items` must be Array (max length: 35).';  
    ^  
`items` must be Array (max length: 35).  
```

**Comment by xynxynxyn** [comment]
Hey, I fixed the issue in commit [02ff1ad](https://github.com/xynxynxyn/terminal-discord/commit/02ff1adb1d106109ca5357457a04ad049bcb0ade)

Thanks for notifying :+1:
