### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by ShayBox** [xynxynxyn/terminal-discord#20]
Could someone make an AUR package?

**Comment by Nikita11790** [comment]
mate its literally npm, so it would be
sudo pacman -S npm (I think)
npm install -g terminal-discord

**Comment by ShayBox** [comment]
That's not the same thing at all

**Comment by Ambyjkl** [comment]
Indeed.

**Comment by ScottyFillups** [comment]
Bump. What's the ETA for the AUR package?

**Comment by xynxynxyn** [comment]
Since I'm not updating/maintaining this project anymore I'm also not interested in maintaining an AUR package.

If anyone is interested in doing that, feel free to, just say something here.

**Comment by ScottyFillups** [comment]
@Ambyjkl
