### ISSUE TITLE
Confusing description of defaultGuild and defaultChannel

### ISSUE THREAD

**Issue by Blacksilver42** [xynxynxyn/terminal-discord#4]
The README doesn't explain it very well. What if I want a Guild that isn't on the first page?

**Comment by xynxynxyn** [comment]
The new channel selection made this a bit more complicated.
If your item is on the first page just take the number -1 as the index.
If it is on another page your index corresponds to
8 * (page_number - 1) + (item_number - 2)

I'll update the README to make it easier to understand.
