### ISSUE TITLE
Have the seperator not go 10 characters out for short names

### ISSUE THREAD

**Issue by The-Soulless** [xynxynxyn/terminal-discord#8]
Make it so that the seperator will just go to the end of names, for example say someone is named "Anon" have the seperator start at the end ("Anon> Hi") instead of extending the full 10 characters

**Comment by xynxynxyn** [comment]
As of [507dc4f](https://github.com/xynxynxyn/terminal-discord/commit/507dc4f115e55e654ca24b8dd25de0bf16e2dd97) you can set `"allign": false` in your config which should do the trick.
Also names are not shortened by default anymore, so set your preferred max name length if you want that.
